# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="af-magic"
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

plugins=(git)

source $ZSH/oh-my-zsh.sh
export EDITOR='nvim'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias mux="tmuxinator"
alias ls="ls -a"
alias python="python3"

# Load Angular CLI autocompletion.
source <(ng completion script)


case $(sw_vers -productVersion) in
    13.*)
        export C_INCLUDE_PATH="/opt/homebrew/include/glib-2.0"
        ;;
    11.*)
        export C_INCLUDE_PATH="/usr/local/include/glib-2.0"
        ;;
    *)
esac

export GOPATH="$HOME/Code/go-lib"
export CLASSPATH="/Library/Saxon/saxon-he-12.4.jar"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# ONLY for local testing
export ENCRYPTION_KEY="5xeE7mY64dp7GlbGu8IJyZ2XqjxT4gmPetaTF//2liI="
