# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="af-magic"
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

plugins=(git)

source $ZSH/oh-my-zsh.sh
export EDITOR='nvim'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias mux="tmuxinator"
alias ls="ls -a"

# Load Angular CLI autocompletion.
source <(ng completion script)


case $(sw_vers -productVersion) in
    13.*)
        export C_INCLUDE_PATH="/opt/homebrew/include/glib-2.0"
        ;;
    11.*)
        export C_INCLUDE_PATH="/usr/local/include/glib-2.0"
        ;;
    *)
esac

export GOPATH="$HOME/Code/go-lib"

export PATH="$PATH:$HOME/Library/Flutter/bin"

export PATH="/opt/homebrew/Cellar/ruby/3.2.2_1/bin:$PATH"
